### ISSUE TITLE
Symfony 7.x

### ISSUE THREAD

**Issue by ellisgl** [tomcri/htmxfony#1]
Currently the requirements restrictions don't allow it to be installed with Symfony 7.x

**Comment by tomcri** [comment]
I haven't tested it on Symfony 7, but hopefully, I will give it a shot this week

**Comment by tacman** [comment]
Any update on this?  Symfony 4 is EOL, the requirements could be changed to only supported Symfony versions, e.g.


        "symfony/framework-bundle": "^5.4 || ^6.3 || ^7.0",
