### ISSUE TITLE
Symfony 7.0.x Compatability.

### ISSUE THREAD

**Issue by KMcCall-CCCRM** [tomcri/htmxfony#5]
Fatal error: Declaration of Htmxfony\Controller\HtmxControllerTrait::renderBlock(Htmxfony\Template\TemplateBlock ...$blocks): Htmxfony\Response\HtmxResponse must be compatible with Symfony\Bundle\FrameworkBundle\Controller\AbstractController::renderBlock(string $view, string $block, array $parameters = [], ?Symfony\Component\HttpFoundation\Response $response = null): Symfony\Component\HttpFoundation\Response in /var/www/html/vendor/tomcri/htmxfony/src/Controller/HtmxControllerTrait.php on line 26

Example Code:
```php
<?php

namespace App\Controller;

use Htmxfony\Controller\HtmxControllerTrait;
use Htmxfony\Request\HtmxRequest;
use Htmxfony\Response\HtmxResponse;
use Htmxfony\Template\TemplateBlock;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Throwable;

class HomeController extends AbstractController
{
    use HtmxControllerTrait;

    /**
     * @throws Throwable
     */
    public function index(HtmxRequest $request): HtmxResponse
    {
        return $this->renderBlock(new TemplateBlock('home/index.html.twig', 'body'));
    }
}
```

**Comment by tomcri** [comment]
Thank you for notify this issue, it seamns that symfony7 compatibility (https://github.com/tomcri/htmxfony/pull/3) wasn't tested properly. I'll try a fix during this weekend.

**Comment by tomcri** [comment]
I fixed it (https://github.com/tomcri/htmxfony/pull/6) in version 1.2.0, as @microThread suggested the cleanest fix was to rename the render and renderBlock methods into htmxRender and htmxRenderBlock to avoid future collisions.
